name: redair2022
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'World'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello ${{ github.event.inputs.name }}!
jobs:
  say_hello:
  build:
    name: Build Executable
    runs-on: windows-latest  # 使用 Windows runner，以便打包為 .exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # PyInstaller 需要 3.8+

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Package with PyInstaller
        run: pyinstaller --onefile sun2022.py --name sun2022

      - name: Upload Executable to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
